final List promptSuggestions = [
  "Change the theme",
  "Turn on dark mode",
  "Toggle one sided chat mode",
  "What's the latest news",
  "Show me some memes",
  "What's the top post on r/AskReddit",
  "What are some side projects being built?",
  "Get my network state and information",
  "Show me 3 beautiful math equations",
  "Show me my device's specs in table form",
  'Tell me my unread text messages?',
  'How many cores does my phone have?',
  'What is the longest call I had?',
  'Is my phone charging?',
  'Do I have any recent missed calls?',
  'What is the sweetest text I got recently?',
  'How many apps do I have?',
  'Write code to find the Fibonacci sequence in Zig?',
  "Write a Python script to check if a number is prime",
  "Show me the latest quotes from famous philosophers",
  "Generate a workout plan for a beginner",
  "Tell me a fun fact about space exploration",
  "How much storage is available on my device?",
  "Generate a random inspirational quote",
  "Write a JavaScript function to reverse a string",
  "Give me a brief history of AI development",
  "Show me the calorie count of a cheeseburger",
  "CSS snippet to create a responsive navigation bar",
  "Generate a to-do list with time slots for productivity.",
  "Give me a summary of the apps I've installed recently",
  "What was the total duration of all calls made today?",
  "Tell me the time zone of my device",
  "How many unread messages do I have?",
  "Summarize my last 3 call in a table?",
  "Give me a summary of my last 5 text messages",
  "Let's play a game",
];
